import 'package:firebase_auth/firebase_auth.dart';
import 'package:travenour_app/database_service.dart';

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final DatabaseService _databaseService = DatabaseService();

  // Sign up new user
  Future<void> signUp({
    required String name,
    required String email,
    required String password,
    String role = 'user', // Default role is 'user'
  }) async {
    try {
      UserCredential userCredential = await _auth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );

      // Get userId generated by Firebase Authentication
      String userId = userCredential.user!.uid;

      // Add user info to Realtime Database
      await _databaseService.addUser(
        userId: userId,
        name: name,
        email: email,
        password: password,
        role: role,
      );
    } catch (e) {
      print('Error during sign up: $e');
      throw e;
    }
  }

  // Sign in existing user
  Future<User?> signIn(String email, String password) async {
    try {
      UserCredential userCredential = await _auth.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
      return userCredential.user;
    } catch (e) {
      print('Error during sign in: $e');
      return null;
    }
  }

  // Sign out
  Future<void> signOut() async {
    try {
      await _auth.signOut();
    } catch (e) {
      print('Error during sign out: $e');
      throw e;
    }
  }
}
