// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_3GodRMCfvUTmlDOC3Da4bIxJYAGoBqY',
    appId: '1:997528313571:web:c706a61d934235d106afd6',
    messagingSenderId: '997528313571',
    projectId: 'test-app-e4dcf',
    authDomain: 'test-app-e4dcf.firebaseapp.com',
    databaseURL: 'https://test-app-e4dcf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-app-e4dcf.appspot.com',
    measurementId: 'G-XD7DR2XY1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6h1FXWkCtkhIs_lr1vCWMhCK4xUuwVqQ',
    appId: '1:997528313571:android:dd88e9c167a2b97706afd6',
    messagingSenderId: '997528313571',
    projectId: 'test-app-e4dcf',
    databaseURL: 'https://test-app-e4dcf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-app-e4dcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZcFQ9hpOqX5-Z1FioxRk4QMuaBT3LQIw',
    appId: '1:997528313571:ios:c91242dd705bcacd06afd6',
    messagingSenderId: '997528313571',
    projectId: 'test-app-e4dcf',
    databaseURL: 'https://test-app-e4dcf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-app-e4dcf.appspot.com',
    iosBundleId: 'com.example.travenourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZcFQ9hpOqX5-Z1FioxRk4QMuaBT3LQIw',
    appId: '1:997528313571:ios:c91242dd705bcacd06afd6',
    messagingSenderId: '997528313571',
    projectId: 'test-app-e4dcf',
    databaseURL: 'https://test-app-e4dcf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-app-e4dcf.appspot.com',
    iosBundleId: 'com.example.travenourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_3GodRMCfvUTmlDOC3Da4bIxJYAGoBqY',
    appId: '1:997528313571:web:971162ea718fc6e006afd6',
    messagingSenderId: '997528313571',
    projectId: 'test-app-e4dcf',
    authDomain: 'test-app-e4dcf.firebaseapp.com',
    databaseURL: 'https://test-app-e4dcf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-app-e4dcf.appspot.com',
    measurementId: 'G-S2ZSSLGLPM',
  );
}
